# Autogenerated wrapper script for cilkrts_jll for i686-linux-gnu
export libcilkrts

JLLWrappers.@generate_wrapper_header("cilkrts")
JLLWrappers.@declare_library_product(libcilkrts, "libcilkrts.so.5")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcilkrts,
        "lib/libcilkrts.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
