# Autogenerated wrapper script for cilkrts_jll for x86_64-apple-darwin
export libcilkrts

JLLWrappers.@generate_wrapper_header("cilkrts")
JLLWrappers.@declare_library_product(libcilkrts, "@rpath/libcilkrts.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcilkrts,
        "lib/libcilkrts.5.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
